### ISSUE TITLE
Show more than one card on the screen at one time

### ISSUE THREAD

**Issue by focusedonfit** [terminatorover/RGCardViewLayout#18]
I would appreciate any help to display more than one card on the screen at the time. It would be ideal to show a little of the card to the left and to the right so that the user knows there are multiple cards in a view (and knows to swipe left or right)

thank you

**Comment by terminatorover** [comment]
As it stands there the one of core ideas of the layout is to have one card at a time. I will however consider your input for the next release of the layout. 
Thanks.
