### ISSUE TITLE
pod

### ISSUE THREAD

**Issue by syrakozz** [terminatorover/RGCardViewLayout#3]
could you plz make it pod

**Comment by bawn** [comment]
I also hope to submit to the pod

**Comment by terminatorover** [comment]
it's now on cocoapods, just need to add it to your Podfile via 
 pod 'RGCardViewLayout','1.0'
and import it via, 
#import  <RGCardViewLayout/RGCardViewLayout.h>
This will give you access to the RGCardViewLayout class
