### ISSUE TITLE
Problem with Slow slide

### ISSUE THREAD

**Issue by bawn** [terminatorover/RGCardViewLayout#8]
I am using the iPhone  6 Simulator to run the demo，Slow slide switch back to the first page when this happens. More out of the view of the lower right corner of the second page
![bug](https://cloud.githubusercontent.com/assets/7238866/6635501/e29610b6-c9a1-11e4-8e66-e5e8cfec5136.png)

**Comment by KittenYang** [comment]
@bawn Just set the `t.m34`  to **= 1.0/-800**

**Comment by bawn** [comment]
@KittenYang Thanks
